### ISSUE TITLE
Rule clarification

### ISSUE THREAD

**Issue by ashtonmeuser** [bradleytaunt/1mb-club#189]
I think it's important to clarify the rules as to which sites may be allowed into the 1MB Club. Specifically, I think further clarity is needed around:
- 1MB and not 1MiB ([Megabyte](https://en.wikipedia.org/wiki/Megabyte) vs [Mebibyte](https://en.wikipedia.org/wiki/Mebibyte))
- Compressed size vs resource size (visible in Chrome DevTools as "transferred over network" and "resource size", respectively)

Note that I'm happy to open a PR for this. However, it seems that the copy on the actual website is not contained in this repo.

**Comment by bradleytaunt** [comment]
Thanks for the feedback! When I get a chance I might make some changes to the description, but for now it is fairly okay in the rule stated on the page:

> Total resources downloaded client-side must not exceed 1 megabyte

This already mentions your concerns that it is *resource* based and uses *megabyte* as the target. Closing for now (will work back around when I get a chance!)
