### ISSUE TITLE
Clarify 1MB threshold is for transferred data, compression allowed

### ISSUE THREAD

**Issue by divbzero** [bradleytaunt/1mb-club#190]
@bradleytaunt love the idea.

Maybe a clarification like the following could be added after the one and only rule: “The 1 megabyte threshold applies to the amount of data *transferred*, including compression if enabled by the server.”

**Comment by bradleytaunt** [comment]
Mentioned in another issue (about roughly the same concept): https://github.com/bradleytaunt/1mb-club/issues/189
