### ISSUE TITLE
alicegg.tech

### ISSUE THREAD

**Issue by zer0tonin** [bradleytaunt/1mb-club#25]
Hello,
https://alicegg.tech is a bit below 1MB in my tests:
![image](https://user-images.githubusercontent.com/7149690/99708566-44a81e80-2a9e-11eb-87e9-662504303895.png)
![image](https://user-images.githubusercontent.com/7149690/99708869-b4b6a480-2a9e-11eb-8a4f-579017b15b02.png)

**Comment by bradleytaunt** [comment]
Added!
