### ISSUE TITLE
Onesdr

### ISSUE THREAD

**Issue by onesdr** [bradleytaunt/1mb-club#496]
Https://onesdr.com

**Comment by RobThree** [comment]
<img src="https://media.tenor.com/images/50d933375c6146ea5ce65517c267b28f/tenor.gif">

<img width="450" alt="Screenshot 2020-11-20 at 05 33 39" src="https://user-images.githubusercontent.com/607888/99758472-105e4d80-2af2-11eb-905b-b2bccb85f801.png">
