### ISSUE TITLE
Consider using more generous page for sr.ht

### ISSUE THREAD

**Issue by ddevault** [bradleytaunt/1mb-club#56]
sourcehut.org is one of the few pages which have images, and it's much bigger than most other pages as a result.

Would you consider something like [sr.ht/projects](https://sr.ht/projects) as a more representative sample?

Thanks for listing us, anyway <3

**Comment by frntn** [comment]
Came here to add sourcehut
While creating the issue I thought "Well, may be Drew already knows about it..."
Yep. Too late 😄
