### ISSUE TITLE
Documentation Request: How to determine total resource size

### ISSUE THREAD

**Issue by dmuth** [bradleytaunt/1mb-club#93]
Hi!  I can think of a few sites worth adding, but I would need to test them first, and I'm not clear on how to easily make a determination of the total size of resources for a page.  

So my ask would be for documentation to be added to the README so that myself and others can easily find out the total size of resources downloaded from a website. 

Thanks!

-- Doug

**Comment by jankapunkt** [comment]
I would also like to know how to count "total" here. Does this mean the total amount of data downloaded by the initial request? What about dynamically loaded content after user interaction?
